import { Link } from "react-router";
import { Sparkles, Users, BookOpen, ArrowRight, BrainCircuit, Star, CheckCircle2, TrendingUp, Zap, Shield, Play } from "lucide-react";
import { ImageWithFallback } from "../components/figma/ImageWithFallback";
import { Button } from "../components/ui/button";
import { Avatar, AvatarFallback } from "../components/ui/avatar";

const STATS = [
  { value: "50K+", label: "Students Guided" },
  { value: "200+", label: "Expert Counselors" },
  { value: "95%", label: "Satisfaction Rate" },
  { value: "8K+", label: "Roadmaps Generated" },
];

const FEATURES = [
  {
    icon: BrainCircuit,
    title: "AI Career Matching",
    description: "Enter your academic details and skills to receive highly tailored career paths generated by advanced AI in seconds.",
    color: "text-blue-600",
    bg: "bg-blue-50",
    border: "border-blue-100",
  },
  {
    icon: Users,
    title: "Expert Counselors",
    description: "Chat with verified career counselors, schedule sessions, and get your AI-generated roadmaps reviewed by professionals.",
    color: "text-purple-600",
    bg: "bg-purple-50",
    border: "border-purple-100",
  },
  {
    icon: BookOpen,
    title: "Step-by-Step Roadmaps",
    description: "Follow detailed guides for specific careers. Save your favorites and download them as PDFs for offline access.",
    color: "text-emerald-600",
    bg: "bg-emerald-50",
    border: "border-emerald-100",
  },
  {
    icon: TrendingUp,
    title: "Career Insights",
    description: "Access hundreds of articles, webinars, and job market data to stay informed and ahead of industry trends.",
    color: "text-orange-600",
    bg: "bg-orange-50",
    border: "border-orange-100",
  },
  {
    icon: Zap,
    title: "Instant Recommendations",
    description: "No waiting — our AI analyzes your profile and delivers personalized career recommendations within moments.",
    color: "text-yellow-600",
    bg: "bg-yellow-50",
    border: "border-yellow-100",
  },
  {
    icon: Shield,
    title: "Verified & Trusted",
    description: "All counselors are background-checked and vetted. Every AI suggestion is reviewed by certified career professionals.",
    color: "text-teal-600",
    bg: "bg-teal-50",
    border: "border-teal-100",
  },
];

const TESTIMONIALS = [
  {
    quote: "CareerPath AI helped me discover I was perfect for UX design. Within 3 months, I had my first internship!",
    name: "Zara Ahmed",
    role: "UX Design Student",
    initials: "ZA",
    color: "from-pink-500 to-rose-600",
    rating: 5,
  },
  {
    quote: "The AI roadmap for software engineering was incredibly detailed. It mapped out exactly what certifications I needed.",
    name: "Lucas Mendez",
    role: "Computer Science Major",
    initials: "LM",
    color: "from-blue-500 to-indigo-600",
    rating: 5,
  },
  {
    quote: "Dr. Jenkins reviewed my plan and caught gaps in my skills I hadn't noticed. Invaluable guidance!",
    name: "Priya Nair",
    role: "Data Science Graduate",
    initials: "PN",
    color: "from-purple-500 to-violet-600",
    rating: 5,
  },
];

const ARTICLES_PREVIEW = [
  {
    id: 1,
    title: "How to Break Into Data Science: A Complete 2026 Roadmap",
    category: "Technology",
    readTime: "8 min",
    image: "https://images.unsplash.com/photo-1585123607190-72ec2979a269?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
    categoryColor: "bg-blue-50 text-blue-700",
  },
  {
    id: 2,
    title: "Resume Writing Tips That Beat Modern ATS Systems",
    category: "Career Tips",
    readTime: "6 min",
    image: "https://images.unsplash.com/photo-1650735311937-1876825e971b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
    categoryColor: "bg-emerald-50 text-emerald-700",
  },
  {
    id: 3,
    title: "The Future of AI in Career Guidance: What Students Should Know",
    category: "Technology",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1655393001768-d946c97d6fd1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
    categoryColor: "bg-blue-50 text-blue-700",
  },
];

const EVENTS = [
  { month: "MAY", day: 15, title: "Global Tech Virtual Career Fair", detail: "Online • 50+ Companies" },
  { month: "MAY", day: 22, title: "MBA Admissions Webinar", detail: "Zoom • Dr. Sarah Jenkins" },
  { month: "JUN", day: 3, title: "Healthcare Careers Summit", detail: "Online • Panel Discussion" },
];

export function GuestHome() {
  return (
    <div className="flex flex-col">
      {/* Hero Section */}
      <section className="relative bg-white overflow-hidden">
        {/* Background gradient decoration */}
        <div className="absolute inset-0 bg-gradient-to-br from-blue-50/80 via-white to-indigo-50/50"></div>
        <div className="absolute top-0 right-0 w-1/2 h-full opacity-30">
          <div className="absolute top-20 right-20 w-64 h-64 bg-blue-300 rounded-full blur-3xl"></div>
          <div className="absolute top-60 right-60 w-48 h-48 bg-indigo-200 rounded-full blur-3xl"></div>
        </div>

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-16 pb-20 flex flex-col lg:flex-row items-center gap-12">
          <div className="lg:w-1/2 flex flex-col items-center lg:items-start text-center lg:text-left">
            <span className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-blue-100 text-blue-700 text-sm font-semibold mb-6">
              <Sparkles className="w-4 h-4" /> AI-Powered Career Guidance
            </span>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-extrabold text-gray-900 tracking-tight leading-tight mb-6">
              Discover Your Perfect{" "}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600">
                Career Path
              </span>{" "}
              with AI
            </h1>
            <p className="text-lg md:text-xl text-gray-600 mb-8 max-w-xl leading-relaxed">
              Get personalized career recommendations based on your skills and academics. Connect with expert counselors to navigate your future with confidence.
            </p>
            <div className="flex flex-col sm:flex-row gap-3 w-full justify-center lg:justify-start">
              <Button asChild size="lg" className="bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white border-0 shadow-lg shadow-blue-200 px-8 h-12">
                <Link to="/signup">
                  Get Started Free <ArrowRight className="ml-2 w-5 h-5" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg" className="border-gray-300 text-gray-700 hover:bg-gray-50 h-12 px-6">
                <Link to="/counselors">
                  <Play className="mr-2 w-4 h-4 text-blue-600" /> Find a Counselor
                </Link>
              </Button>
            </div>

            {/* Trust indicators */}
            <div className="flex items-center gap-3 mt-8">
              <div className="flex -space-x-2">
                {["ZA", "LM", "PN", "RS"].map((initials, i) => (
                  <div key={i} className="w-8 h-8 rounded-full bg-gradient-to-br from-blue-400 to-indigo-500 border-2 border-white flex items-center justify-center text-white text-[10px] font-bold shadow-sm">
                    {initials}
                  </div>
                ))}
              </div>
              <div className="text-sm text-gray-600">
                <span className="font-bold text-gray-900">50,000+</span> students already guided
              </div>
            </div>
          </div>

          {/* Hero Image */}
          <div className="lg:w-1/2 w-full max-w-lg lg:max-w-none">
            <div className="relative">
              <div className="rounded-2xl overflow-hidden shadow-2xl border border-gray-100 aspect-[4/3]">
                <ImageWithFallback
                  src="https://images.unsplash.com/photo-1661555144338-093c85f8c588?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2xsZWdlJTIwc3R1ZGVudCUyMHN0dWR5aW5nfGVufDF8fHx8MTc3ODU1OTE3OHww&ixlib=rb-4.1.0&q=80&w=800"
                  alt="Student studying on laptop"
                  className="object-cover w-full h-full"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-blue-900/20 to-transparent"></div>
              </div>

              {/* Floating card */}
              <div className="absolute -bottom-4 -left-4 bg-white rounded-xl shadow-xl p-4 border border-gray-100 max-w-48">
                <div className="flex items-center gap-2 mb-2">
                  <div className="w-8 h-8 bg-green-100 rounded-lg flex items-center justify-center">
                    <CheckCircle2 className="w-4 h-4 text-green-600" />
                  </div>
                  <div>
                    <p className="text-xs font-bold text-gray-900 leading-none">AI Match Found!</p>
                    <p className="text-[10px] text-gray-500 mt-0.5">98% compatibility</p>
                  </div>
                </div>
                <p className="text-xs text-blue-700 font-semibold bg-blue-50 px-2 py-1 rounded-md">Machine Learning Engineer</p>
              </div>

              <div className="absolute -top-4 -right-4 bg-white rounded-xl shadow-xl p-3 border border-gray-100">
                <div className="flex items-center gap-1.5">
                  <Star className="w-4 h-4 text-amber-400 fill-amber-400" />
                  <span className="text-sm font-bold text-gray-900">4.9</span>
                </div>
                <p className="text-[10px] text-gray-500 mt-1">Top Rated Platform</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Bar */}
      <section className="bg-gray-900 text-white py-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            {STATS.map((s) => (
              <div key={s.label}>
                <div className="text-3xl font-extrabold text-white mb-1">{s.value}</div>
                <div className="text-sm text-gray-400">{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="bg-gray-50 py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-14">
            <span className="text-sm font-semibold text-blue-600 uppercase tracking-wider">Everything You Need</span>
            <h2 className="mt-3 text-3xl md:text-4xl font-bold text-gray-900">Your complete career toolkit</h2>
            <p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">
              From AI-driven recommendations to expert human guidance — all in one seamless platform.
            </p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {FEATURES.map((feature) => (
              <div key={feature.title} className={`bg-white p-7 rounded-2xl shadow-sm border ${feature.border} hover:shadow-md transition-all hover:-translate-y-0.5 group`}>
                <div className={`w-11 h-11 ${feature.bg} rounded-xl flex items-center justify-center ${feature.color} mb-5`}>
                  <feature.icon className="w-5 h-5" />
                </div>
                <h3 className="font-bold text-gray-900 mb-2 text-lg">{feature.title}</h3>
                <p className="text-gray-600 text-sm leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-14">
            <span className="text-sm font-semibold text-blue-600 uppercase tracking-wider">Simple Process</span>
            <h2 className="mt-3 text-3xl font-bold text-gray-900">Get started in 3 easy steps</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              { step: "01", title: "Create Your Profile", desc: "Sign up and enter your academic background, skills, and interests.", icon: "📝" },
              { step: "02", title: "Get AI Recommendations", desc: "Our AI analyzes your profile and suggests the best-fit career paths.", icon: "🤖" },
              { step: "03", title: "Follow Your Roadmap", desc: "Review your roadmap with a counselor and start taking action!", icon: "🚀" },
            ].map((s, i) => (
              <div key={s.step} className="text-center relative">
                {i < 2 && (
                  <div className="hidden md:block absolute top-10 left-full w-full h-0.5 border-t-2 border-dashed border-gray-200 -translate-x-1/2 z-0"></div>
                )}
                <div className="relative z-10">
                  <div className="w-20 h-20 bg-gradient-to-br from-blue-50 to-indigo-100 rounded-2xl flex items-center justify-center text-3xl mx-auto mb-5 shadow-sm border border-blue-100">
                    {s.icon}
                  </div>
                  <span className="text-xs font-bold text-blue-500 tracking-widest">STEP {s.step}</span>
                  <h3 className="font-bold text-gray-900 mt-1 mb-2 text-lg">{s.title}</h3>
                  <p className="text-gray-600 text-sm leading-relaxed">{s.desc}</p>
                </div>
              </div>
            ))}
          </div>
          <div className="text-center mt-12">
            <Button asChild size="lg" className="bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white border-0 shadow-lg px-10 h-12">
              <Link to="/signup">Start Your Journey <ArrowRight className="ml-2 w-5 h-5" /></Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Articles Preview */}
      <section className="py-20 bg-gray-50 border-t border-gray-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-end mb-10">
            <div>
              <span className="text-sm font-semibold text-blue-600 uppercase tracking-wider">Knowledge Hub</span>
              <h2 className="mt-2 text-3xl font-bold text-gray-900">Latest Career Insights</h2>
              <p className="mt-2 text-gray-600">Expert-written articles to fuel your career journey.</p>
            </div>
            <Link to="/articles" className="hidden sm:flex items-center gap-1.5 text-blue-600 font-semibold hover:text-blue-700 transition-colors">
              View All <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {ARTICLES_PREVIEW.map((article) => (
              <Link to="/articles" key={article.id} className="group bg-white rounded-2xl border border-gray-100 overflow-hidden shadow-sm hover:shadow-lg transition-all hover:-translate-y-0.5 cursor-pointer block">
                <div className="aspect-[16/9] overflow-hidden">
                  <ImageWithFallback
                    src={article.image}
                    alt={article.title}
                    className="object-cover w-full h-full group-hover:scale-105 transition-transform duration-500"
                  />
                </div>
                <div className="p-5">
                  <div className="flex items-center gap-2 mb-3">
                    <span className={`text-xs font-semibold px-2.5 py-1 rounded-lg ${article.categoryColor}`}>
                      {article.category}
                    </span>
                    <span className="text-xs text-gray-400">{article.readTime} read</span>
                  </div>
                  <h3 className="font-bold text-gray-900 group-hover:text-blue-600 transition-colors line-clamp-2 leading-snug">
                    {article.title}
                  </h3>
                </div>
              </Link>
            ))}
          </div>
          <div className="mt-6 text-center sm:hidden">
            <Link to="/articles" className="inline-flex items-center gap-1.5 text-blue-600 font-semibold hover:text-blue-700">
              View All Articles <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <span className="text-sm font-semibold text-blue-600 uppercase tracking-wider">Success Stories</span>
            <h2 className="mt-3 text-3xl font-bold text-gray-900">Students love CareerPath AI</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {TESTIMONIALS.map((t) => (
              <div key={t.name} className="bg-gray-50 rounded-2xl p-6 border border-gray-100">
                <div className="flex mb-4">
                  {[...Array(t.rating)].map((_, i) => (
                    <Star key={i} className="w-4 h-4 text-amber-400 fill-amber-400" />
                  ))}
                </div>
                <p className="text-gray-700 text-sm leading-relaxed mb-5 italic">"{t.quote}"</p>
                <div className="flex items-center gap-3">
                  <Avatar className="w-9 h-9">
                    <AvatarFallback className={`bg-gradient-to-br ${t.color} text-white text-xs font-bold`}>
                      {t.initials}
                    </AvatarFallback>
                  </Avatar>
                  <div>
                    <p className="text-sm font-bold text-gray-900 leading-none">{t.name}</p>
                    <p className="text-xs text-gray-500 mt-0.5">{t.role}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Events Section */}
      <section className="py-20 bg-gray-900 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row justify-between items-center gap-10">
          <div className="md:w-1/2">
            <span className="text-sm font-semibold text-blue-400 uppercase tracking-wider">Upcoming</span>
            <h2 className="mt-3 text-3xl font-bold mb-4">Job Fairs & Events</h2>
            <p className="text-gray-300 mb-6 leading-relaxed">
              Stay updated with campus recruitment drives, virtual job fairs, and industry webinars hosted by our counselors.
            </p>
            <Button variant="outline" className="bg-transparent border-white/30 text-white hover:bg-white/10 hover:text-white h-11 px-6">
              View Full Calendar <ArrowRight className="ml-2 w-4 h-4" />
            </Button>
          </div>
          <div className="md:w-1/2 w-full">
            <div className="space-y-3">
              {EVENTS.map((event, i) => (
                <div key={i} className="flex gap-4 p-4 rounded-xl bg-white/5 hover:bg-white/10 transition-colors cursor-pointer border border-white/5">
                  <div className="flex flex-col items-center justify-center bg-blue-600/20 rounded-xl min-w-14 h-14 border border-blue-500/30 shrink-0">
                    <span className="text-[10px] text-blue-300 font-bold uppercase">{event.month}</span>
                    <span className="text-xl font-extrabold text-white leading-none">{event.day}</span>
                  </div>
                  <div className="flex flex-col justify-center">
                    <h4 className="font-bold text-white text-sm">{event.title}</h4>
                    <p className="text-xs text-gray-400 mt-1">{event.detail}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 bg-gradient-to-br from-blue-600 to-indigo-700 text-white">
        <div className="max-w-3xl mx-auto px-4 text-center">
          <div className="w-16 h-16 bg-white/10 rounded-2xl flex items-center justify-center mx-auto mb-6">
            <Sparkles className="w-8 h-8 text-white" />
          </div>
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Ready to find your ideal career?</h2>
          <p className="text-blue-100 text-lg mb-8">
            Join 50,000+ students already using CareerPath AI to build their futures.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button asChild size="lg" className="bg-white text-blue-700 hover:bg-blue-50 border-0 shadow-xl font-bold h-12 px-8">
              <Link to="/signup">Create Free Account</Link>
            </Button>
            <Button asChild variant="outline" size="lg" className="bg-transparent border-white/40 text-white hover:bg-white/10 hover:text-white h-12 px-8">
              <Link to="/counselors">Browse Counselors</Link>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
}
